name: flutter_pda_scanner_v2_example
description: "Demonstrates how to use the flutter_pda_scanner_v2 plugin."
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.3.3 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter

  flutter_pda_scanner_v2:
    # When depending on this package from a real application you should use:
    #   flutter_pda_scanner_v2: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  cupertino_icons: ^1.0.6

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
