name: flutter_pda_scanner_v2
description: "Flutter plugin that supports wide range of PDA handheld scanner devices."
homepage: https://github.com/michaelchiew08/flutter_pda_scanner_v2
version: 0.0.3

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=2.18.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ztt.flutter_pda_scanner_v2
        pluginClass: PdaScannerPlugin
      ios:
        pluginClass: PdaScannerPlugin
